export const AppImages = {
  splashbackground: require('../assets/images/splashbackground.png'),
  splashlogo: require('../assets/images/splashlogo.png'),
  Loginbackground: require('../assets/images/Loginbackground.png'),
  emial: require('../assets/images/email.png'),
  whatsapp: require('../assets/images/whatsapp.png'),
  wechat: require('../assets/images/wechat.png'),
  Google: require('../assets/images/Google.png'),
  Vector: require('../assets/images/Vector.png'),
  documentverification: require('../assets/images/documentverification.png'),
  selectcountrycode: require('../assets/images/selectcountrycode.png'),
  Ellipse: require('../assets/images/Ellipse.png'),
  profile: require('../assets/images/profile.png'),
  tick: require('../assets/images/tick.png'),
  USA: require('../assets/images/USA.png'),
  Uk: require('../assets/images/Uk.png'),
  carditem: require('../assets/images/cardright.png'),
  bakground: require('../assets/images/bakground.png'),
  // img: require('../assets/images/img.png'),
  notification: require('../assets/images/notification.png'),
  white: require('../assets/images/white.png'),
  black: require('../assets/images/black.png'),
  search: require('../assets/images/search.png'),
  // homeicon: require('../assets/images/homeicon.png'),
  activity: require('../assets/images/activity.png'),
  inventory: require('../assets/images/inventory.png'),
  inbox: require('../assets/images/inbox.png'),
  more: require('../assets/images/more.png'),
  nodata: require('../assets/images/nodata.png'),
  tik: require('../assets/images/tik.png'),
  men: require('../assets/images/men.png'),
  fltr: require('../assets/images/fltr.png'),
  time: require('../assets/images/time.png'),
  logo: require('../assets/images/logo.png'),
  leftarrow: require('../assets/images/leftarrow.png'),
  pencil: require('../assets/images/pencil.png'),
  contract: require('../assets/images/contract.png'),
  goldtik: require('../assets/images/goldtik.png'),
  location: require('../assets/images/location.png'),
  sms: require('../assets/images/sms.png'),
  user: require('../assets/images/user.png'),
  phon: require('../assets/images/phon.png'),
  Star: require('../assets/images/Star.png'),
  Ell: require('../assets/images/Ell.png'),
  note: require('../assets/images/note.png'),
  camera: require('../assets/images/camera.png'),
  circle: require('../assets/images/circle.png'),
  message: require('../assets/images/message.png'),
  itemcard: require('../assets/images/itemcard.png'),
  heart: require('../assets/images/heart.png'),
  rolex: require('../assets/images/hdwatch.png'),
  rolex1: require('../assets/images/hdwatch1.png'),
  rolexshadow: require('../assets/images/rolexshadow.png'),
  certificate1: require('../assets/images/certificate1.png'),
  certificate2: require('../assets/images/certificate2.png'),
  plusbutton: require('../assets/images/plusbutton.png'),
  redheart: require('../assets/images/redheart.png'),
  dh: require('../assets/images/dh.png'),
  rolex3: require('../assets/images/rolex3.png'),
  Subtract: require('../assets/images/Subtract.png'),
  logoBottom: require('../assets/images/logoBottom.png'),
  searchicon: require('../assets/images/searchicon.png'),
  arrowback: require('../assets/images/arrowback.png'),
  bottomtab: require('../assets/images/bottomTab.png'),
  timecraft: require('../assets/images/timecraft.png'),
  // united: require('../assets/images/united.png'),
  trash: require('../assets/images/trash.png'),
  edit: require('../assets/images/edit.png'),
  rolexwatch: require('../assets/images/rolexwatch.png'),
  rainbow: require('../assets/images/rainbow.png'),
  certificate3: require('../assets/images/certificate3.png'),
  certificate4: require('../assets/images/certificate4.png'),
  homesearch: require('../assets/images/homesearch.png'),
  rename: require('../assets/images/rename.png'),
  editprofile: require('../assets/images/editprofile.png'),
  // image1: require('../assets/images/image1.png'),
  // image2: require('../assets/images/image2.png'),
  // image3: require('../assets/images/image3.png'),
  // image4: require('../assets/images/image4.png'),
  // image5: require('../assets/images/image5.png'),
  // image6: require('../assets/images/image6.png'),
  // image7: require('../assets/images/image7.png'),
  microphone: require('../assets/images/microphone.png'),
  microphoneslash: require('../assets/images/microphoneslash.png'),
  pin: require('../assets/images/pin.png'),
  unpin: require('../assets/images/unpin.png'),
  crossvector: require('../assets/images/Vectorcross.png'),
  arrowleft: require('../assets/images/arrowleft.png'),

  Group: require('../assets/images/Group.png'),

  note: require('../assets/images/note.png'),
  link: require('../assets/images/link.png'),
  // redit: require('../assets/images/redit.png'),
  business: require('../assets/images/business.png'),
  dummyprofile: require('../assets/images/dummyprofile.png'),
  searchiconflag: require('../assets/images/searchiconflag.png'),
  dealerimg: require('../assets/images/dealerimg.png'),
  editbusinessimg: require('../assets/images/editbusinessimg.png'),
  searchnormal: require('../assets/images/searchnormal.png'),
  seconddummy: require('../assets/images/seconddummy.png'),
  customwatch: require('../assets/images/customwatch.png'),
  sear: require('../assets/images/sear.png'),
  dotss: require('../assets/images/dotss.png'),
  pinnn: require('../assets/images/pinnn.png'),
  happyy: require('../assets/images/happyy.png'),
  loc: require('../assets/images/loc.png'),
  Gellry: require('../assets/images/Gellry.png'),
  cameraicon: require('../assets/images/cameraicon.png'),
  mutee: require('../assets/images/mutee.png'),
  sentt: require('../assets/images/sentt.png'),
  blockk: require('../assets/images/blockk.png'),
  mediaa: require('../assets/images/mediaa.png'),
  profileid: require('../assets/images/profileid.png'),
  shopp: require('../assets/images/shopp.png'),
  unmutee: require('../assets/images/unmutee.png'),
  rightarow: require('../assets/images/rightarow.png'),
  delete: require('../assets/images/delete.png'),
  reportt: require('../assets/images/reportt.png'),
  homes: require('../assets/images/homes.png'),
  nosms: require('../assets/images/smsnotification.png'),
  videoplay: require('../assets/images/videoplay.png'),
  pdf: require('../assets/images/pdf.png'),

  doc: require('../assets/images/docicon.png'),
  manuallyproduct: require('../assets/images/manuallyproduct.png'),
  manuallyproduct1: require('../assets/images/manuallyproduct1.png'),
  manuallyproduct2: require('../assets/images/manuallyproduct2.png'),
  manuallyproduct3: require('../assets/images/manuallyproduct3.png'),
  chk: require('../assets/images/chk.png'),
  untickk: require('../assets/images/untickk.png'),
  ar: require('../assets/images/ar.png'),
  productimageshadow: require('../assets/images/productimageshadow.png'),
  productimg1: require('../assets/images/productimg1.png'),
  productimg2: require('../assets/images/productimg2.png'),
  productimg3: require('../assets/images/productimg3.png'),
  archive: require('../assets/images/archive.png'),
  ccircle: require('../assets/images/ccircle.png'),

  imageicon: require('../assets/images/imageicon.png'),
  xlsxicon: require('../assets/images/xlsxicon.png'),
  othericon: require('../assets/images/othericon.png'),
  photoicon: require('../assets/images/photo.png'),
  videocircle: require('../assets/images/videocircle.png'),
  document: require('../assets/images/document.png'),
  mapcircle: require('../assets/images/mapcircle.png'),
  sendlocation: require('../assets/images/sendlocation.png'),
  sharelocation: require('../assets/images/sharelocation.png'),
  audiocircle: require('../assets/images/audiocircle.png'),
  playicon: require('../assets/images/playicon.png'),
  MapMarker: require('../assets/images/MapMarker.png'),
  tickbadge: require('../assets/images/tickbadge.png'),
  stoprecording: require('../assets/images/stoprecording.png'),
  homescreen: require('../assets/images/homescreen.png'),
  notify: require('../assets/images/notify.png'),
};
