export const CountryCodes = [
  { name: "Pakistan", code: "pk", dialCode: "92" ,flag:require("../assets/flags/Pakistan.png")},

  { name: "Afghanistan", code: "af", dialCode: "93" ,flag:require("../assets/flags/Afghanistan.png")},
  { name: "Albania", code: "al", dialCode: "355",flag:require("../assets/flags/Albania.png")},
  { name: "Algeria", code: "dz", dialCode: "213" ,flag:require("../assets/flags/Algeria.png")},
  { name: "Andorra", code: "ad", dialCode: "376" ,flag:require("../assets/flags/Andorra.png")},
  { name: "Angola", code: "ao", dialCode: "244" ,flag:require("../assets/flags/Angola.png")},
  { name: "Antigua and Barbuda", code: "ag", dialCode: "1-268" ,flag:require("../assets/flags/AntiguaBarbuda.png")},
  { name: "Argentina", code: "ar", dialCode: "54" ,flag:require("../assets/flags/Argentina.png")},
  { name: "Armenia", code: "am", dialCode: "374" ,flag:require("../assets/flags/Armenia.png")},
  { name: "Australia", code: "au", dialCode: "61" ,flag:require("../assets/flags/Australia.png")},
  { name: "Austria", code: "at", dialCode: "43" ,flag:require("../assets/flags/Austria.png")},
  { name: "Azerbaijan", code: "az", dialCode: "994",flag:require("../assets/flags/Azerbaijan.png") },
  { name: "Bahamas", code: "bs", dialCode: "1-242" ,flag:require("../assets/flags/Bahamas.png")},
  { name: "Bahrain", code: "bh", dialCode: "973" ,flag:require("../assets/flags/Bahrain.png")},
  { name: "Bangladesh", code: "bd", dialCode: "880" ,flag:require("../assets/flags/Bangladesh.png")},
  { name: "Barbados", code: "bb", dialCode: "1-246" ,flag:require("../assets/flags/Barbados.png")},
  { name: "Belarus", code: "by", dialCode: "375" ,flag:require("../assets/flags/Belarus.png")},
  { name: "Belgium", code: "be", dialCode: "32" ,flag:require("../assets/flags/Belgium.png")},
  { name: "Belize", code: "bz", dialCode: "501" ,flag:require("../assets/flags/Belize.png")},
  { name: "Benin", code: "bj", dialCode: "229" ,flag:require("../assets/flags/Benin.png")},
  { name: "Bhutan", code: "bt", dialCode: "975" ,flag:require("../assets/flags/Bhutan.png")},
  { name: "Bolivia", code: "bo", dialCode: "591" ,flag:require("../assets/flags/Bolivia.png")},
  { name: "Bosnia and Herzegovina", code: "ba", dialCode: "387" ,flag:require("../assets/flags/BosniaHerzegovina.png")},
  { name: "Botswana", code: "bw", dialCode: "267" ,flag:require("../assets/flags/Botswana.png")},
  { name: "Brazil", code: "br", dialCode: "55" ,flag:require("../assets/flags/Brazil.png")},
  { name: "Brunei", code: "bn", dialCode: "673" ,flag:require("../assets/flags/Brunei.png")},
  { name: "Bulgaria", code: "bg", dialCode: "359" ,flag:require("../assets/flags/Bulgaria.png")},
  { name: "Burkina Faso", code: "bf", dialCode: "226",flag:require("../assets/flags/BurkinaFaso.png") },
  { name: "Burundi", code: "bi", dialCode: "257" ,flag:require("../assets/flags/Burundi.png")},
  { name: "Cabo Verde", code: "cv", dialCode: "238" ,flag:require("../assets/flags/CaboVerde.png")},
  { name: "Cambodia", code: "kh", dialCode: "855" ,flag:require("../assets/flags/Cambodia.png")},
  { name: "Cameroon", code: "cm", dialCode: "237" ,flag:require("../assets/flags/Cameroon.png")},
  { name: "Canada", code: "ca", dialCode: "1" ,flag:require("../assets/flags/Canada.png")},
  // { name: "Central African Republic", code: "cf", dialCode: "236" ,flag:require("../assets/flags/Central African Republic.png")},
  { name: "Chad", code: "td", dialCode: "235" ,flag:require("../assets/flags/Chad.png")},
  { name: "Chile", code: "cl", dialCode: "56" ,flag:require("../assets/flags/Chile.png")},
  { name: "China", code: "cn", dialCode: "86" ,flag:require("../assets/flags/China.png")},
  { name: "Colombia", code: "co", dialCode: "57" ,flag:require("../assets/flags/Colombia.png")},
  { name: "Comoros", code: "km", dialCode: "269" ,flag:require("../assets/flags/Comoros.png")},
  // { name: "Congo (Democratic Republic of the)", code: "cd", dialCode: "243" ,flag:require("../assets/flags/Congo (Democratic Republic of the).png")},
  // { name: "Congo (Republic of the)", code: "cg", dialCode: "242" ,flag:require("../assets/flags/Congo (Republic of the).png")},
  { name: "Costa Rica", code: "cr", dialCode: "506" ,flag:require("../assets/flags/CostaRica.png")},
  { name: "Croatia", code: "hr", dialCode: "385" ,flag:require("../assets/flags/Croatia.png")},
  { name: "Cuba", code: "cu", dialCode: "53" ,flag:require("../assets/flags/Cuba.png")},
  { name: "Cyprus", code: "cy", dialCode: "357" ,flag:require("../assets/flags/Cyprus.png")},
  // { name: "Czech Republic", code: "cz", dialCode: "420" ,flag:require("../assets/flags/Czech Republic.png")},
  { name: "Denmark", code: "dk", dialCode: "45" ,flag:require("../assets/flags/Denmark.png")},
  { name: "Djibouti", code: "dj", dialCode: "253" ,flag:require("../assets/flags/Djibouti.png")},
  { name: "Dominica", code: "dm", dialCode: "1-767",flag:require("../assets/flags/Dominica.png") },
  { name: "Dominican Republic", code: "do", dialCode: "1-809",flag:require("../assets/flags/DominicanRepublic.png") },
  // { name: "East Timor", code: "tl", dialCode: "670" ,flag:require("../assets/flags/East Timor.png")},
  { name: "Ecuador", code: "ec", dialCode: "593" ,flag:require("../assets/flags/Ecuador.png")},
  { name: "Egypt", code: "eg", dialCode: "20" ,flag:require("../assets/flags/Egypt.png")},
  { name: "El Salvador", code: "sv", dialCode: "503" ,flag:require("../assets/flags/ElSalvador.png")},
  { name: "Equatorial Guinea", code: "gq", dialCode: "240",flag:require("../assets/flags/EquatorialGuinea.png") },
  { name: "Eritrea", code: "er", dialCode: "291" ,flag:require("../assets/flags/Eritrea.png")},
  { name: "Estonia", code: "ee", dialCode: "372" ,flag:require("../assets/flags/Estonia.png")},
  { name: "Eswatini", code: "sz", dialCode: "268" ,flag:require("../assets/flags/Eswatini.png")},
  { name: "Ethiopia", code: "et", dialCode: "251" ,flag:require("../assets/flags/Ethiopia.png")},
  { name: "Fiji", code: "fj", dialCode: "679" ,flag:require("../assets/flags/Fiji.png")},
  { name: "Finland", code: "fi", dialCode: "358" ,flag:require("../assets/flags/Finland.png")},
  { name: "France", code: "fr", dialCode: "33" ,flag:require("../assets/flags/France.png")},
  { name: "Gabon", code: "ga", dialCode: "241",flag:require("../assets/flags/Gabon.png") },
  { name: "Gambia", code: "gm", dialCode: "220" ,flag:require("../assets/flags/Gambia.png")},
  { name: "Georgia", code: "ge", dialCode: "995" ,flag:require("../assets/flags/Georgia.png")},
  { name: "Germany", code: "de", dialCode: "49",flag:require("../assets/flags/Germany.png") },
  { name: "Ghana", code: "gh", dialCode: "233" ,flag:require("../assets/flags/Ghana.png")},
  { name: "Greece", code: "gr", dialCode: "30" ,flag:require("../assets/flags/Greece.png")},
  { name: "Grenada", code: "gd", dialCode: "1-473" ,flag:require("../assets/flags/Grenada.png")},
  { name: "Guatemala", code: "gt", dialCode: "502" ,flag:require("../assets/flags/Guatemala.png")},
  { name: "Guinea", code: "gn", dialCode: "224" ,flag:require("../assets/flags/Guinea.png")},
  { name: "Guinea-Bissau", code: "gw", dialCode: "245" ,flag:require("../assets/flags/Guinea-Bissau.png")},
  { name: "Guyana", code: "gy", dialCode: "592" ,flag:require("../assets/flags/Guyana.png")},
  { name: "Haiti", code: "ht", dialCode: "509" ,flag:require("../assets/flags/Haiti.png")},
  { name: "Honduras", code: "hn", dialCode: "504" ,flag:require("../assets/flags/Honduras.png")},
  { name: "Hungary", code: "hu", dialCode: "36" ,flag:require("../assets/flags/Hungary.png")},
  { name: "Iceland", code: "is", dialCode: "354" ,flag:require("../assets/flags/Iceland.png")},
  { name: "India", code: "in", dialCode: "91" ,flag:require("../assets/flags/India.png")},
  { name: "Indonesia", code: "id", dialCode: "62",flag:require("../assets/flags/Indonesia.png") },
  { name: "Iran", code: "ir", dialCode: "98" ,flag:require("../assets/flags/Iran.png")},
  { name: "Iraq", code: "iq", dialCode: "964" ,flag:require("../assets/flags/Iraq.png")},
  { name: "Ireland", code: "ie", dialCode: "353" ,flag:require("../assets/flags/Ireland.png")},
  { name: "Israel", code: "il", dialCode: "972",flag:require("../assets/flags/Israel.png") },
  { name: "Italy", code: "it", dialCode: "39" ,flag:require("../assets/flags/Italy.png")},
  { name: "Jamaica", code: "jm", dialCode: "1-876",flag:require("../assets/flags/Jamaica.png") },
  { name: "Japan", code: "jp", dialCode: "81" ,flag:require("../assets/flags/Japan.png")},
  { name: "Jordan", code: "jo", dialCode: "962" ,flag:require("../assets/flags/Jordan.png")},
  { name: "Kazakhstan", code: "kz", dialCode: "7" ,flag:require("../assets/flags/Kazakhstan.png")},
  { name: "Kenya", code: "ke", dialCode: "254" ,flag:require("../assets/flags/Kenya.png")},
  { name: "Kiribati", code: "ki", dialCode: "686" ,flag:require("../assets/flags/Kiribati.png")},
  // { name: "Korea (North)", code: "kp", dialCode: "+850",flag:require("../assets/flags/Korea (North).png") },
  // { name: "Korea (South)", code: "kr", dialCode: "+82" ,flag:require("../assets/flags/Korea (South).png")},
  // { name: "Kosovo", code: "xk", dialCode: "+383" ,flag:require("../assets/flags/Kosovo.png")},
  { name: "Kuwait", code: "kw", dialCode: "965" ,flag:require("../assets/flags/Kuwait.png")},
  { name: "Kyrgyzstan", code: "kg", dialCode: "996" ,flag:require("../assets/flags/Kyrgyzstan.png")},
  { name: "Laos", code: "la", dialCode: "856" ,flag:require("../assets/flags/Laos.png")},
  { name: "Latvia", code: "lv", dialCode: "371" ,flag:require("../assets/flags/Latvia.png")},
  { name: "Lebanon", code: "lb", dialCode: "961" ,flag:require("../assets/flags/Lebanon.png")},
  { name: "Lesotho", code: "ls", dialCode: "266" ,flag:require("../assets/flags/Lesotho.png")},
  { name: "Liberia", code: "lr", dialCode: "231" ,flag:require("../assets/flags/Liberia.png")},
  { name: "Libya", code: "ly", dialCode: "218" ,flag:require("../assets/flags/Libya.png")},
  { name: "Liechtenstein", code: "li", dialCode: "423" ,flag:require("../assets/flags/Liechtenstein.png")},
  { name: "Lithuania", code: "lt", dialCode: "370" ,flag:require("../assets/flags/Lithuania.png")},
  { name: "Luxembourg", code: "lu", dialCode: "352" ,flag:require("../assets/flags/Luxembourg.png")},
  { name: "Madagascar", code: "mg", dialCode: "261" ,flag:require("../assets/flags/Madagascar.png")},
  { name: "Malawi", code: "mw", dialCode: "265" ,flag:require("../assets/flags/Malawi.png")},
  { name: "Malaysia", code: "my", dialCode: "60" ,flag:require("../assets/flags/Malaysia.png")},
  { name: "Maldives", code: "mv", dialCode: "960" ,flag:require("../assets/flags/Maldives.png")},
  { name: "Mali", code: "ml", dialCode: "223" ,flag:require("../assets/flags/Mali.png")},
  { name: "Malta", code: "mt", dialCode: "356" ,flag:require("../assets/flags/Malta.png")},
  { name: "Marshall Islands", code: "mh", dialCode: "692",flag:require("../assets/flags/MarshallIslands.png") },
  { name: "Mauritania", code: "mr", dialCode: "222" ,flag:require("../assets/flags/Mauritania.png")},
  { name: "Mauritius", code: "mu", dialCode: "230" ,flag:require("../assets/flags/Mauritius.png")},
  { name: "Mexico", code: "mx", dialCode: "52",flag:require("../assets/flags/Mexico.png") },
  { name: "Micronesia", code: "fm", dialCode: "691" ,flag:require("../assets/flags/Micronesia.png")},
  { name: "Moldova", code: "md", dialCode: "373" ,flag:require("../assets/flags/Moldova.png")},
  { name: "Monaco", code: "mc", dialCode: "377" ,flag:require("../assets/flags/Monaco.png")},
  { name: "Mongolia", code: "mn", dialCode: "976" ,flag:require("../assets/flags/Mongolia.png")},
  { name: "Montenegro", code: "me", dialCode: "382" ,flag:require("../assets/flags/Montenegro.png")},
  { name: "Morocco", code: "ma", dialCode: "212" ,flag:require("../assets/flags/Morocco.png")},
  { name: "Mozambique", code: "mz", dialCode: "258" ,flag:require("../assets/flags/Mozambique.png")},
  { name: "Myanmar", code: "mm", dialCode: "95" ,flag:require("../assets/flags/Myanmar.png")},
  { name: "Namibia", code: "na", dialCode: "264" ,flag:require("../assets/flags/Namibia.png")},
  { name: "Nauru", code: "nr", dialCode: "674" ,flag:require("../assets/flags/Nauru.png")},
  { name: "Nepal", code: "np", dialCode: "977" ,flag:require("../assets/flags/Nepal.png")},
  { name: "Netherlands", code: "nl", dialCode: "31" ,flag:require("../assets/flags/Netherlands.png")},
  { name: "New Zealand", code: "nz", dialCode: "64" ,flag:require("../assets/flags/NewZealand.png")},
  { name: "Nicaragua", code: "ni", dialCode: "505" ,flag:require("../assets/flags/Nicaragua.png")},
  { name: "Niger", code: "ne", dialCode: "227" ,flag:require("../assets/flags/Niger.png")},
  { name: "Nigeria", code: "ng", dialCode: "234" ,flag:require("../assets/flags/Nigeria.png")},
  { name: "North Macedonia", code: "mk", dialCode: "389" ,flag:require("../assets/flags/NorthMacedonia.png")},
  { name: "Norway", code: "no", dialCode: "47" ,flag:require("../assets/flags/Norway.png")},
  { name: "Oman", code: "om", dialCode: "968" ,flag:require("../assets/flags/Oman.png")},
  // { name: "Pakistan", code: "pk", dialCode: "92" ,flag:require("../assets/flags/Pakistan.png")},
  { name: "Palau", code: "pw", dialCode: "680" ,flag:require("../assets/flags/Palau.png")},
  { name: "Panama", code: "pa", dialCode: "507" ,flag:require("../assets/flags/Panama.png")},
  { name: "Papua New Guinea", code: "pg", dialCode: "675" ,flag:require("../assets/flags/PapuaNewGuinea.png")},
  { name: "Paraguay", code: "py", dialCode: "595",flag:require("../assets/flags/Paraguay.png") },
  { name: "Peru", code: "pe", dialCode: "51" ,flag:require("../assets/flags/Peru.png")},
  { name: "Philippines", code: "ph", dialCode: "63",flag:require("../assets/flags/Philippines.png") },
  // { name: "Poland", code: "pl", dialCode: "+48",flag:require("../assets/flags/Poland.png") },
  { name: "Portugal", code: "pt", dialCode: "351" ,flag:require("../assets/flags/Portugal.png")},
  { name: "Qatar", code: "qa", dialCode: "974" ,flag:require("../assets/flags/Qatar.png")},
  { name: "Romania", code: "ro", dialCode: "40" ,flag:require("../assets/flags/Romania.png")},
  { name: "Russia", code: "ru", dialCode: "7" ,flag:require("../assets/flags/Russia.png")},
  { name: "Rwanda", code: "rw", dialCode: "250" ,flag:require("../assets/flags/Rwanda.png")},
  { name: "Saint Kitts and Nevis", code: "kn", dialCode: "1-869" ,flag:require("../assets/flags/SaintKittsandNevis.png")},
  { name: "Saint Lucia", code: "lc", dialCode: "+1-758" ,flag:require("../assets/flags/SaintLucia.png")},
  // { name: "Saint Vincent and the Grenadines", code: "vc", dialCode: "+1-784" ,flag:require("../assets/flags/Saint Vincent and the Grenadines.png")},
  { name: "Samoa", code: "ws", dialCode: "685",flag:require("../assets/flags/Samoa.png") },
  { name: "San Marino", code: "sm", dialCode: "378" ,flag:require("../assets/flags/SanMarino.png")},
  { name: "Sao Tome and Principe", code: "st", dialCode: "239",flag:require("../assets/flags/SaoTomeandPrincipe.png") },
  { name: "Saudi Arabia", code: "sa", dialCode: "966" ,flag:require("../assets/flags/SaudiArabia.png")},
  { name: "Senegal", code: "sn", dialCode: "221" ,flag:require("../assets/flags/Senegal.png")},
  { name: "Serbia", code: "rs", dialCode: "381" ,flag:require("../assets/flags/Serbia.png")},
  { name: "Seychelles", code: "sc", dialCode: "248" ,flag:require("../assets/flags/Seychelles.png")},
  { name: "Sierra Leone", code: "sl", dialCode: "232" ,flag:require("../assets/flags/SierraLeone.png")},
  { name: "Singapore", code: "sg", dialCode: "65" ,flag:require("../assets/flags/Singapore.png")},
  { name: "Slovakia", code: "sk", dialCode: "421" ,flag:require("../assets/flags/Slovakia.png")},
  { name: "Slovenia", code: "si", dialCode: "386" ,flag:require("../assets/flags/Slovenia.png")},
  { name: "Solomon Islands", code: "sb", dialCode: "677" ,flag:require("../assets/flags/SolomonIslands.png")},
  { name: "Somalia", code: "so", dialCode: "252" ,flag:require("../assets/flags/Somalia.png")},
  { name: "South Africa", code: "za", dialCode: "27" ,flag:require("../assets/flags/SouthAfrica.png")},
  { name: "South Sudan", code: "ss", dialCode: "211" ,flag:require("../assets/flags/SouthSudan.png")},
  { name: "Spain", code: "es", dialCode: "34" ,flag:require("../assets/flags/Spain.png")},
  { name: "Sri Lanka", code: "lk", dialCode: "94" ,flag:require("../assets/flags/SriLanka.png")},
  { name: "Sudan", code: "sd", dialCode: "249",flag:require("../assets/flags/Sudan.png") },
  { name: "Suriname", code: "sr", dialCode: "597" ,flag:require("../assets/flags/Suriname.png")},
  { name: "Sweden", code: "se", dialCode: "46" ,flag:require("../assets/flags/Sweden.png")},
  { name: "Switzerland", code: "ch", dialCode: "41",flag:require("../assets/flags/Switzerland.png") },
  { name: "Syria", code: "sy", dialCode: "963",flag:require("../assets/flags/Syria.png") },
  // { name: "Taiwan", code: "tw", dialCode: "+886" ,flag:require("../assets/flags/Taiwan.png")},
  { name: "Tajikistan", code: "tj", dialCode: "992",flag:require("../assets/flags/Tajikistan.png") },
  { name: "Tanzania", code: "tz", dialCode: "255" ,flag:require("../assets/flags/Tanzania.png")},
  { name: "Thailand", code: "th", dialCode: "66" ,flag:require("../assets/flags/Thailand.png")},
  { name: "Togo", code: "tg", dialCode: "228" ,flag:require("../assets/flags/Togo.png")},
  { name: "Tonga", code: "to", dialCode: "676" ,flag:require("../assets/flags/Tonga.png")},
  { name: "Trinidad and Tobago", code: "tt", dialCode: "1-868",flag:require("../assets/flags/TrinidadandTobago.png") },
  { name: "Tunisia", code: "tn", dialCode: "216" ,flag:require("../assets/flags/Tunisia.png")},
  { name: "Turkey", code: "tr", dialCode: "90" ,flag:require("../assets/flags/Turkey.png")},
  { name: "Turkmenistan", code: "tm", dialCode: "993" ,flag:require("../assets/flags/Turkmenistan.png")},
  { name: "Tuvalu", code: "tv", dialCode: "688" ,flag:require("../assets/flags/Tuvalu.png")},
  { name: "Uganda", code: "ug", dialCode: "256" ,flag:require("../assets/flags/Uganda.png")},
  { name: "Ukraine", code: "ua", dialCode: "380" ,flag:require("../assets/flags/Ukraine.png")},
  { name: "UAE", code: "ae", dialCode: "971" ,flag:require("../assets/flags/UAE.png")},
  { name: "UK", code: "gb", dialCode: "44" ,flag:require("../assets/flags/UK.png")},
  { name: "USA", code: "us", dialCode: "1" ,flag:require("../assets/flags/USA.png")},
  { name: "Uruguay", code: "uy", dialCode: "598" ,flag:require("../assets/flags/Uruguay.png")},
  { name: "Uzbekistan", code: "uz", dialCode: "998" ,flag:require("../assets/flags/Argentina.png")},
  { name: "Vanuatu", code: "vu", dialCode: "678" ,flag:require("../assets/flags/Vanuatu.png")},
  // { name: "Vatican City", code: "va", dialCode: "+39-06",flag:require("../assets/flags/Vatican City.png") },
  { name: "Venezuela", code: "ve", dialCode: "58" ,flag:require("../assets/flags/Venezuela.png")},
  { name: "Vietnam", code: "vn", dialCode: "84" ,flag:require("../assets/flags/Vietnam.png")},
  { name: "Yemen", code: "ye", dialCode: "967" ,flag:require("../assets/flags/Yemen.png")},
  { name: "Zambia", code: "zm", dialCode: "260" ,flag:require("../assets/flags/Zambia.png")},
  { name: "Zimbabwe", code: "zw", dialCode: "263" ,flag:require("../assets/flags/Zimbabwe.png")}
];